dist: trusty
sudo: false
language: cpp

# safelist
branches:
  only:
  - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - libtbb-dev

script:
    - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9
    - ./build.sh all  
