dist: trusty
sudo: false
language: cpp

# safelist
branches:
  only:
  - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
            - libtbb-dev

script:
    - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
    - ./build.sh all  
